{ ... }: {
  wayland.windowManager.hyprland = {
    settings = {

     monitor = "eDP-1,1680x1050@90,auto,1.20"; 
     "autogenerated" = "0";
     "$mainMod" = "SUPER";
     "$terminal" = "kitty";

      # Xwayland
      xwayland = {
        force_zero_scaling = true;
      };

      # Noctalia Theme
      "source" = [
        "~/.config/hypr/noctalia/noctalia-colors.conf"
      ];

      # Start Noctalia when Hyprland boots
      "exec-once" = [
        "noctalia-shell"
        "hyprpaper"
      ];     

      # Dynamic Gaps: Apply a larger outer gap when exactly 1 tiled window is visible
      workspace = [
        "w[tv1], gapsout:120"
      ];

      # Environment Variables
      "env" = [
        "XCURSOR_SIZE,15"
      ];

      # Input Devices
      "input" = {
        "kb_layout" = "us";
        "follow_mouse" = "1";
        "touchpad" = {
          "natural_scroll" = "false";
        };
        "sensitivity" = "0"; # -1.0 - 1.0, 0 means no modification.
      };

      # General Window Layout
      "general" = {
        "gaps_in" = "10";
        "gaps_out" = "20";
        "border_size" = "1";
        "layout" = "dwindle";
      };

      # Window Decoration
      "decoration" = {
        "rounding" = "0";
        "blur" = {
          "enabled" = "true";
          "size" = "3";
          "passes" = "1";
        };
      };

      # Animations
      "animations" = {
        "enabled" = "yes";
        "bezier" = "myBezier, 0.05, 0.9, 0.1, 1.05";
        "animation" = [
          "windows, 1, 7, myBezier"
          "windowsOut, 1, 7, default, popin 80%"
          "border, 1, 10, default"
          "borderangle, 1, 8, default"
          "fade, 1, 7, default"
          "workspaces, 1, 6, default"
        ];
      };

      # Keybindings
      "bind" = [
         "$mainMod, t, exec, $terminal"
        "$mainMod, q, killactive"
        "$mainMod, Space, togglefloating"       
        "$mainMod, f, exec, noctalia-shell ipc call launcher toggle"
        "$mainMod, Delete, exec, noctalia-shell ipc call controlCenter toggle"
        "$mainMod SHIFT, b, exec, noctalia-shell ipc call bar toggle" 
        "$mainMod SHIFT, Delete, exec, noctalia-shell ipc call lockScreen lock"   


      # Move focus 
        "$mainMod, l, movefocus, l"
        "$mainMod, h, movefocus, r"
        "$mainMod, j, movefocus, u"
        "$mainMod, k, movefocus, d"
        "$mainMod SHIFT, f, fullscreen" 


      # Resized window
        "$mainMod ALT, h, resizeactive, -20 0"
        "$mainMod ALT, j, resizeactive, 0 20"
        "$mainMod ALT, k, resizeactive, 0 -20"
        "$mainMod ALT, l, resizeactive, 20 0"

      # Move active window
        "$mainMod SHIFT, h, movewindow, l"
        "$mainMod SHIFT, j, movewindow, d"
        "$mainMod SHIFT, k, movewindow, u"
        "$mainMod SHIFT, l, movewindow, r"

      # Switch workspaces with mainMod + [4-12]
        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, 6, workspace, 6"
        "$mainMod, 7, workspace, 7"
        "$mainMod, 8, workspace, 8"
        "$mainMod, 9, workspace, 9"
        "$mainMod, 0, workspace, 10"

      # Move active window to a workspace with mainMod + SHIFT + [4-12]
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod SHIFT, 6, movetoworkspace, 6"
        "$mainMod SHIFT, 7, movetoworkspace, 7"
        "$mainMod SHIFT, 8, movetoworkspace, 8"
        "$mainMod SHIFT, 9, movetoworkspace, 9"
        "$mainMod SHIFT, 0, movetoworkspace, 10"
      ];

      # 'bindel' applies the 'e' (repeating) and 'l' (locked) flags [2]
      # This allows you to hold down the key to adjust settings, even on the lock screen.
      "bindel" = [
        ", XF86MonBrightnessUp, exec, noctalia-shell ipc call brightness increase"
        ", XF86MonBrightnessDown, exec, noctalia-shell ipc call brightness decrease"
        ", XF86AudioRaiseVolume, exec, noctalia-shell ipc call volume increase"
        ", XF86AudioLowerVolume, exec, noctalia-shell ipc call volume decrease"
      ];

      # 'bindl' applies the 'l' (locked) flag for toggles [2]
      # This allows mute toggles to work on the lock screen without repeating.
      "bindl" = [
        ", XF86AudioMute, exec, noctalia-shell ipc call volume muteOutput"
        ", XF86AudioMicMute, exec, noctalia-shell ipc call volume muteInput"
      ];
        
      # Move/resize windows with mainMod + LMB/RMB and dragging
      "bindm" = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];
    };
  };
}
